language: php
php:
  - 5.6
  - hhvm
  - nightly
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
script: phpunit
matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
notifications:
    on_success: never
    on_failure: always